"""Secret words the bot picks for solo games."""

import random

from word_duel.game_logic import is_valid_word, normalize_word


def _words(length, *blocks):
    seen = []
    for block in blocks:
        for raw in block.split():
            word = normalize_word(raw)
            if is_valid_word(word, length) and word not in seen:
                seen.append(word)
    return tuple(seen)


WORDS = {
    3: _words(
        3,
        "ACE ADD AGE AID AIM AIR ANT APE ARC ARM ART ASH AWE "
        "BAG BAT BAY BED BEE BID BIG BIN BIT BOW BOX BOY BUD BUG BUN BUS "
        "CAB CAN CAP CAR CAT COB COD COP COW CUB CUP CUT "
        "DAD DAM DAY DEN DEW DIG DIP DOG DOT DRY DUE DUG DYE "
        "EAR EAT EEL EGG ELK ELM END ERA EVE EYE "
        "FAN FAR FAT FIG FIN FIT FIX FLY FOG FOX FRY FUN FUR "
        "GAP GAS GEL GEM GIN GOD GUM GUN GUT GUY "
        "HAM HAT HAY HEN HID HIP HIT HOG HOP HOT HUB HUE HUG HUM HUT "
        "ICE INK INN IVY "
        "JAM JAR JAW JAY JET JOB JOG JOY JUG "
        "KEG KEY KID KIN KIT "
        "LAB LAD LAP LAW LAY LEG LID LIE LIP LOG LOT LOW "
        "MAD MAN MAP MAT MIX MOB MOP MUD MUG "
        "NAP NET NIP NOD NUT "
        "OAK OAR OAT OIL ONE ORE OWL "
        "PAD PAN PAW PEA PEN PET PIE PIG PIN PIT POD POP POT PUP "
        "RAG RAM RAT RAY RED RIB RIG RIM ROB ROD ROW RUB RUG RUM RUN "
        "SAD SAP SAW SEA SIN SIP SKI SKY SOB SON SOW SPY SUM SUN "
        "TAB TAG TAN TAP TAR TEA TEN TIE TIN TIP TOE TON TOP TOY TUB TUG "
        "URN "
        "VAN VET VOW "
        "WAG WAR WAX WAY WEB WET WIG WIN WIT WOK WOW "
        "YAK YAM YES YEW "
        "ZAP ZEN ZIP ZOO",
    ),
    4: _words(
        4,
        "ABLE ACID ACRE AGED ALSO AREA ARMY AUNT AUTO AWAY AXIS "
        "BABY BACK BAIT BAKE BALL BAND BANG BANK BARE BARK BARN BASE BASS BATH BEAD BEAK BEAM BEAN BEAR BEAT BEEF BELL BELT BEND BENT BEST BIKE BILL BIND BIRD BITE BLUE BOAT BODY BOIL BOLD BONE BOOK BOOT BORE BORN BOSS BOTH BOWL BULB BULK BULL BUMP BURN BUSH BUSY "
        "CAFE CAGE CAKE CALF CALL CALM CAME CAMP CARD CARE CART CASE CASH CAST CAVE CHAT CHEF CHIN CHIP CHOP CITY CLAM CLAP CLAW CLAY CLIP CLUB CLUE COAL COAT CODE COIL COIN COLD COLT COMB COME COOK COOL CORD CORE CORK CORN COST CRAB CROW CLUB CUBE CULT CURB CURE CURL CUTE "
        "DAMP DARE DARK DART DATA DATE DAWN DEAD DEAL DEAR DECK DEEP DEER DESK DIAL DICE DIET DIME DIRT DISH DIVE DOCK DOLL DONE DOOM DOOR DOSE DOWN DRAG DRAW DREW DRIP DROP DRUM DUCK DUEL DUKE DUNE DUNK DUSK DUST DUTY "
        "EACH EARN EAST EASY ECHO EDGE EDIT EGGS ELSE EVEN EVER EVIL EXAM EXIT "
        "FACE FACT FADE FAIL FAIR FALL FAME FARM FAST FATE FEAR FEED FEEL FEET FELL FELT FERN FILE FILL FILM FIND FINE FIRE FIRM FISH FIST FIVE FLAG FLAT FLAW FLEA FLED FLEE FLIP FLOW FOAM FOLD FOLK FOOD FOOL FOOT FORD FORK FORM FORT FOUL FOUR FREE FROG FROM FUEL FULL FUME FUND "
        "GAIN GAME GANG GATE GAVE GEAR GIFT GIRL GIVE GLAD GLOW GLUE GOAL GOAT GOLD GOLF GONE GOOD GOWN GRAB GRAM GRAY GREW GRID GRIM GRIN GRIP GROW GULF GUST "
        "HAIR HALF HALL HALT HAND HANG HARD HARE HARM HATE HAVE HEAD HEAL HEAP HEAR HEAT HEEL HELD HELL HELP HERB HERD HERE HERO HIDE HIGH HILL HINT HIRE HOLD HOLE HOME HONE HOOK HOOP HOPE HORN HOSE HOST HOUR HUGE HULL HUNT HURT HUSH HYMN "
        "ICED ICON IDEA IDLE INCH INTO IRON ITEM "
        "JACK JADE JAIL JAZZ JOIN JOKE JUMP JURY JUST "
        "KEEN KEEP KICK KIND KING KISS KITE KNEE KNEW KNIT KNOB KNOT KNOW "
        "LACE LACK LADY LAID LAKE LAMB LAMP LAND LANE LARK LAST LATE LAVA LAWN LAZY LEAD LEAF LEAN LEAP LEFT LEND LENS LESS LIAR LIFT LIKE LILY LIME LINE LINK LION LIST LIVE LOAD LOAF LOAN LOCK LOFT LONG LOOK LOOP LORD LOSE LOSS LOST LOUD LOVE LUCK LUNG "
        "MADE MAIL MAIN MAKE MALE MALL MALT MANY MARE MARK MARS MASK MASS MAST MATH MEAL MEAN MEAT MEET MELT MENU MESS MICE MILD MILE MILK MILL MIND MINE MINT MISS MIST MOAT MODE MOLD MOLE MONK MOON MORE MOSS MOST MOTH MOVE MUCH MULE MUST MYTH "
        "NAIL NAME NAVY NEAR NEAT NECK NEED NEST NEWS NEXT NICE NINE NONE NOON NOSE NOTE NOUN NUMB "
        "OAKS OATH OBEY OILS OKAY ONCE ONLY ONTO OPEN OVEN OVER "
        "PACE PACK PAGE PAID PAIL PAIN PAIR PALE PALM PARK PART PASS PAST PATH PAVE PEAK PEAR PEAS PEEL PEER PELT PEST PICK PILE PILL PINE PINK PINT PIPE PITY PLAN PLAY PLEA PLOT PLUG PLUS POEM POET POKE POLE POLL POND PONY POOL POOR POPE PORK PORT POSE POST POUR PRAY PREY PULL PULP PUMP PURE PUSH "
        "QUIZ "
        "RACE RACK RAFT RAGE RAID RAIL RAIN RAKE RANK RARE RATE READ REAL REAR REED REEF REEL REIN RELY REST RICE RICH RIDE RING RISE RISK ROAD ROAR ROBE ROCK RODE ROLL ROOF ROOM ROOT ROPE ROSE RUBY RUDE RULE RUSH RUST "
        "SACK SAFE SAGE SAID SAIL SAKE SALE SALT SAME SAND SANG SANK SAVE SEAL SEAM SEAT SEED SEEK SEEM SEEN SELF SELL SEND SHED SHIP SHOE SHOP SHOT SHOW SHUT SICK SIDE SIGH SIGN SILK SILO SING SINK SITE SIZE SKIN SKIP SLAB SLAM SLID SLIM SLIP SLOW SNAP SNOW SOAP SOCK SODA SOFA SOFT SOIL SOLD SOLE SOME SONG SOON SORE SORT SOUL SOUP SOUR SPIN SPIT SPOT STAR STAY STEM STEP STEW STIR STOP SUCH SUIT SURE SWAN SWIM "
        "TACK TAIL TAKE TALE TALK TALL TANK TAPE TASK TEAM TEAR TELL TENT TERM TEST TEXT THAN THAT THEM THEN THEY THIN THIS TIDY TIED TIER TILE TILL TIME TINY TIRE TOAD TOES TOLD TOLL TOMB TONE TOOL TORN TOSS TOUR TOWN TREE TRIM TRIP TUBE TUNA TUNE TURN TWIN TYPE "
        "UGLY UNIT UPON USED USER "
        "VAIN VARY VASE VAST VEIL VEIN VENT VERY VEST VETO VICE VIEW VINE VOID VOTE "
        "WADE WAGE WAIT WAKE WALK WALL WARM WARN WASH WAVE WAXY WEAK WEAR WEEK WELL WENT WERE WEST WHAT WHEN WHIP WHOM WIDE WIFE WILD WILL WILT WIND WINE WING WINK WINS WIPE WIRE WISE WISH WOLF WOOD WOOL WORD WORE WORK WORM WORN WRAP YARD YARN YEAR YELL YOUR "
        "ZERO ZONE ZOOM",
    ),
    5: _words(
        5,
        "CRANE HOUSE PLANT WATER TIGER APPLE BREAD CHAIR TRAIN MUSIC "
        "LIGHT STORM RIVER HEART SMILE CLOUD GRAPE LEMON PEACH BERRY "
        "WORLD EARTH OCEAN FIELD FOREST DANCE MAGIC STORY NIGHT DREAM "
        "SWEET SHARP QUICK BRAVE HAPPY QUIET FRESH CLEAN GREEN BROWN "
        "STONE GLASS PAPER CLOCK RADIO PIANO HORSE SHEEP MOUSE "
        "SNAKE EAGLE WHALE ZEBRA CAMEL PANDA ROBOT CANDY "
        "PIZZA PASTA SALAD JUICE HONEY SUGAR CREAM "
        "TABLE SOFA LAMP DOOR FLOOR "
        "BEACH MOUNT VALLEY PLAIN CREEK MARSH SWAMP "
        "CROWN SWORD SHIELD ARMOR PRINCE QUEEN "
        "TRACE SLATE AUDIO ADIEU RAISE STEAL POINT BRICK "
        "FLAME SPARK SMOKE STEAM FROST BLAZE FLASH SHINE "
        "ABOUT ABOVE ACTOR ACUTE ADMIT ADOPT ADULT AFTER AGAIN AGENT AGREE AHEAD ALARM ALBUM ALERT ALIEN ALIGN ALIKE ALIVE ALLOW ALONE ALONG ALOUD ALPHA ALTAR ALTER AMBER AMEND AMONG ANGEL ANGER ANGLE ANGRY APART APPLE APPLY ARENA ARGUE ARISE ARRAY ARROW ASIDE ASSET ATLAS ATOMS AUDIO AUDIT AVOID AWARD AWARE AWFUL "
        "BADGE BADLY BAGEL BAKED BAKER BALLS BANJO BARGE BASIC BASIN BASIS BATCH BATHE BEACH BEANS BEARD BEAST BEGIN BEING BELLY BELOW BENCH BERRY BIGOT BIRTH BLACK BLADE BLAME BLAND BLANK BLAST BLAZE BLEED BLEND BLESS BLIND BLINK BLOCK BLOOD BLOOM BLOWN BLUES BLUFF BLUNT BLUSH BOARD BOOST BOOTH BOUND BOXER BRAIN BRAND BRASS BRAVE BREAD BREAK BREED BRICK BRIDE BRIEF BRING BRISK BROAD BROKE BROWN BRUSH BUILD BUILT BUNCH BURST BUYER "
        "CABIN CABLE CAMEL CANDY CANOE CARGO CAROL CARRY CARVE CATCH CAUSE CHAIN CHAIR CHALK CHARM CHART CHASE CHEAP CHEAT CHECK CHESS CHEST CHIEF CHILD CHILL CHINA CHOIR CHORD CIVIL CLAIM CLASH CLASS CLEAN CLEAR CLERK CLICK CLIFF CLIMB CLOAK CLOCK CLONE CLOSE CLOTH CLOUD CLOWN COACH COAST COBRA COCOA COLOR COMET COMIC CORAL COUCH COUGH COULD COUNT COURT COVER CRACK CRAFT CRANE CRASH CRAWL CRAZE CRAZY CREAM CREPT CRIME CRISP CROOK CROSS CROWD CROWN CRUEL CRUSH CURVE CYCLE "
        "DAILY DAIRY DANCE DATED DEALT DEATH DEBIT DEBUT DECAY DECOR DELAY DELTA DEMON DENIM DENSE DEPOT DEPTH DEVIL DIARY DIGIT DINER DIRTY DISCO DITCH DIVER DIZZY DONUT DOUBT DOUGH DOZEN DRAFT DRAIN DRAMA DRANK DRAWN DREAM DRESS DRIED DRIFT DRILL DRINK DRIVE DROVE DROWN EAGER EAGLE EARLY EARTH EIGHT ELBOW ELDER ELECT EMPTY ENACT ENEMY ENJOY ENTER ENTRY EQUAL ERROR ESSAY EVENT EVERY EXACT EXIST EXTRA "
        "FABLE FACED FAINT FAIRY FAITH FALSE FANCY FATAL FATTY FAULT FAVOR FEAST FENCE FEVER FIBER FIELD FIFTH FIFTY FIGHT FINAL FIRST FIXED FLAME FLARE FLASH FLEET FLESH FLICK FLIGHT FLOAT FLOCK FLOOD FLOOR FLORA FLOUR FLUID FLUSH FLUTE FOCUS FORCE FORGE FORTH FORUM FOUND FRAME FRANK FRESH FRIED FRONT FROST FROWN FRUIT FUDGE FULLY FUNNY "
        "GIANT GIVEN GLASS GLEAM GLIDE GLOBE GLORY GLOVE GRADE GRAIN GRAND GRANT GRAPE GRAPH GRASP GRASS GRAVE GRAVY GREAT GREED GREEN GREET GRILL GRIND GROSS GROUP GROVE GROWL GROWN GUARD GUESS GUEST GUIDE GUILD GUILT "
        "HABIT HAPPY HARDY HARSH HASTE HATCH HATED HAUNT HAVEN HAZEL HEADY HEART HEAVY HEDGE HELLO HENCE HERBS HEROES HIKER HILLS HINGE HOBBY HONEY HONOR HORSE HOTEL HOUND HOUSE HUMAN HUMID HUMOR HURRY "
        "IDEAL IMAGE IMPLY INDEX INNER INPUT IRONY ISSUE IVORY "
        "JEANS JELLY JEWEL JOINT JOKER JUDGE JUICE "
        "KARMA KNEEL KNIFE KNOCK KNOWN "
        "LABEL LABOR LEMON LEVEL LIGHT LIMIT LINEN LIVER LOCAL LODGE LOGIC LOOSE LOSER LOVER LOWER LOYAL LUNCH LYRIC "
        "MACRO MAGIC MAJOR MAKER MANGO MAPLE MARCH MATCH MAYBE MAYOR MEDAL MEDIA MELON MERCY MERGE MERIT MERRY METAL METER MICRO MIGHT MINOR MINUS MIXED MODEL MONEY MONTH MORAL MOTOR MOUNT MOUSE MOUTH MOVIE MUSIC "
        "NAKED NASAL NASTY NAVAL NEEDY NERVE NEVER NEWLY NIGHT NOBLE NOISE NORTH NOVEL NURSE "
        "OCEAN OFFER OFTEN OLIVE ONION OPERA ORBIT ORDER ORGAN OTHER OUGHT OUTER OWNER OXIDE "
        "PAINT PANEL PANIC PAPER PARKA PARTY PASTA PASTE PATCH PAUSE PEACE PEACH PEARL PENNY PERCH PHASE PHONE PHOTO PIANO PIECE PILOT PITCH PIVOT PIXEL PLACE PLAID PLAIN PLANE PLANT PLATE PLAZA PLEAD PLOT PLUS PLUSH POACH POINT POISE POKER POLAR PORCH POUND POWER PRESS PRICE PRIDE PRIME PRINT PRIZE PROOF PROUD PROVE PROXY PUPIL PURSE "
        "QUEEN QUERY QUEST QUEUE QUICK QUIET QUILT QUIRK QUITE QUOTE "
        "RADAR RADIO RAINY RAISE RALLY RANGE RAPID RATIO REACH REACT READY REALM REBEL RENEW REPLY RIDER RIDGE RIGHT RINSE RIVAL RIVER ROAST ROBIN ROBOT ROCKY ROUGH ROUND ROUTE ROYAL RUGBY RULER RUMOR RURAL "
        "SADLY SAINT SALAD SCALE SCARE SCENE SCENT SCOPE SCORE SCOUT SCRAP SENSE SERVE SETUP SEVEN SHADE SHAKE SHALL SHAME SHAPE SHARE SHARK SHARP SHAVE SHEEP SHEER SHEET SHELF SHELL SHIFT SHINE SHIRT SHOCK SHOOT SHORE SHORT SHOUT SHOWN SIDED SIGHT SILLY SINCE SIREN SIXTH SIXTY SKATE SKILL SKIRT SKULL SLACK SLAIN SLANG SLEEP SLICE SLIDE SLOPE SMALL SMART SMELL SMILE SMOKE SNAIL SNAKE SNACK SNEAK SOLAR SOLID SOLVE SORRY SOUND SOUTH SPACE SPADE SPARE SPARK SPEAK SPEAR SPEED SPELL SPEND SPICE SPIKE SPILL SPINE SPLIT SPOIL SPOKE SPORT SPOTS SPRAY SQUAD STACK STAFF STAGE STAIR STAKE STALE STALK STALL STAMP STAND STARE START STATE STEAK STEAL STEAM STEEL STEEP STEER STICK STILL STING STOCK STONE STORE STORM STORY STOVE STRAP STRAW STRAY STUCK STUDY STUFF STUMP STYLE SUGAR SUITE SUNNY SUPER SWAMP SWEET SWING SWORD "
        "TABLE TASTE TEACH TEETH THANK THEIR THEME THERE THESE THICK THIEF THING THINK THIRD THOSE THREE THROW THUMB TIGER TIGHT TIMER TITLE TOAST TODAY TOKEN TOOTH TOPIC TOTAL TOUCH TOUGH TOWER TRACK TRADE TRAIN TRAIT TRASH TREAT TREND TRIAL TRIBE TRICK TRUCK TRULY TRUNK TRUST TRUTH TULIP TUMOR TUNIC TWICE TWIST "
        "UNCLE UNDER UNION UNITE UNITY UNTIL UPPER URBAN USAGE USUAL "
        "VAGUE VALID VALUE VALVE VAPOR VAULT VENUE VIDEO VIRUS VISIT VITAL VIVID VOCAL VOICE VOTER "
        "WAGON WAIST WASTE WATCH WATER WEARY WEIGH WEIRD WHALE WHEAT WHEEL WHERE WHICH WHILE WHITE WHOLE WHOSE WIDOW WIDTH WOMAN WORLD WORRY WORSE WORST WORTH WOULD WOUND WRITE WRONG WROTE "
        "YIELD YOUNG YOUTH "
        "ZEBRA",
    ),
    6: _words(
        6,
        "MONKEY PLANET ROCKET GARDEN CASTLE FOREST ORANGE BANANA "
        "PURPLE YELLOW SILVER GOLDEN WINTER SUMMER SPRING AUTUMN "
        "BRIDGE ISLAND VALLEY STREAM FLOWER PUZZLE SECRET GUITAR "
        "DRAGON KNIGHT WIZARD TEMPLE MARKET SCHOOL FRIEND FAMILY "
        "ABSENT ACCENT ACCEPT ACCESS ACCUSE ACROSS ACTION ACTIVE ACTUAL ADVICE ADVISE AFFECT AFFORD AFRAID ALMOST ALWAYS AMOUNT ANIMAL ANNUAL ANSWER ANYONE ANYWAY APPEAL APPEAR AROUND ARRIVE ARTIST ASPECT ATTACK ATTEND AUTHOR AVENUE "
        "BACKED BACKUP BALLET BAMBOO BANANA BANKER BANNER BARBER BARELY BARREL BATTLE BEAUTY BECOME BEFORE BEHALF BEHAVE BEHIND BELIEF BELONG BESIDE BETTER BEYOND BINARY BITTER BORDER BOTTLE BOTTOM BOUGHT BRANCH BREATH BRIDGE BRIGHT BROKEN BRONZE BRUSHED BUCKET BUDGET BUFFER BUMBLE BUNDLE BURDEN BUREAU BURIED BURNED BUTTER BUTTON "
        "CAMERA CAMPUS CANAL CANDLE CANNOT CANVAS CARBON CAREER CARPET CARROT CASTLE CASUAL CAUGHT CENTER CHANCE CHANGE CHARGE CHEESE CHERRY CHOICE CHOOSE CHOSEN CHURCH CINEMA CIRCLE CLIENT CLOSET CLOUDY COFFEE COLLAR COLUMN COMBAT COMEDY COMING COMMON COOKIE COPPER CORNER COSMIC COTTON COUNTY COUPLE COURSE COUSIN COVERS CRAZY CREATE CREDIT CRISIS CRYSTAL CUSTOM "
        "DAMAGE DANCER DANGER DEBATE DECADE DECIDE DEFEAT DEFEND DEFINE DEGREE DEMAND DENIAL DENTAL DEPEND DESERT DESIGN DESIRE DETAIL DETECT DEVICE DINNER DIRECT DIVIDE DOCTOR DOLLAR DOMAIN DONATE DOUBLE DOCTOR DOZENS DRAGON DRAWER DRIVEN DRIVER DURING "
        "EASILY EDITOR EFFECT EFFORT EITHER ELEVEN EMPIRE EMPLOY ENABLE ENERGY ENGAGE ENGINE ENOUGH ENTIRE ESCAPE EUROPE EVENTS EXCEPT EXPECT EXPERT EXPORT EXTEND EXTENT "
        "FABRIC FACTOR FAILED FAIRLY FAMILY FAMOUS FARMER FATHER FELLOW FEMALE FIGURE FILTER FINGER FINISH FLAVOR FLIGHT FLOWER FLYING FOLDER FOLLOW FORCED FOREST FORMAL FORMER FOSSIL FOUGHT FOURTH FREEZE FRENCH FRIDAY FRIDGE FRIEND FROZEN FUTURE "
        "GALAXY GALLON GARAGE GARDEN GATHER GENDER GENTLE GIFTED GINGER GLOBAL GOLDEN GOSSIP GOVERN GROUND GROWTH GUITAR "
        "HAMMER HAPPEN HARBOR HEALTH HEAVEN HEIGHT HELPED HIDDEN HOCKEY HOLDER HOLIDAY HONEST HUNGER HUNTER "
        "IGNORE IMPACT IMPORT INCOME INDEED INDOOR INFANT INFORM INJURY INSECT INSIDE INTEND INTENT INVEST ISLAND ITSELF "
        "JACKET JUNGLE "
        "KIDNEY KITTEN KNIGHT "
        "LADDER LAWYER LEADER LEAGUE LENGTH LESSON LETTER LIQUID LITTLE LIVING LOCATE LONELY LOVELY LUMBER LUXURY "
        "MAGNET MAINLY MAKER MANAGE MANNER MANUAL MARBLE MARGIN MARINE MARKER MARKET MASTER MATTER MEDIUM MELODY MEMBER MEMORY MENTAL MERELY METHOD MIDDLE MINUTE MIRROR MOBILE MODERN MODEST MOMENT MONKEY MOSTLY MOTHER MOTION MUSEUM MUSCLE MUTUAL MYSELF "
        "NARROW NATION NATIVE NATURE NEARBY NEARLY NICKEL NIGHTS NOBODY NORMAL NOTICE NUMBER "
        "OBJECT OBTAIN OFFICE ONLINE OPPOSE OPTION ORANGE ORIGIN OXYGEN "
        "PACKET PALACE PARENT PARTLY PENCIL PEOPLE PERSON PHRASE PICKED PICNIC PILLOW PIRATE PLANET PLAYER PLEASE PLENTY POCKET POETRY POLICE POLICY POTATO POWDER PRAISE PREFER PRETTY PRINCE PRISON PROFIT PROPER PUBLIC PUDDLE PURPLE PUZZLE "
        "RABBIT RANDOM RARELY RATHER READER REALLY REASON RECALL RECENT RECIPE RECORD REDUCE REFUSE REGARD REGION REJECT RELATE RELIEF REMAIN REMOTE REPAIR REPEAT REPORT RESCUE RESULT RETIRE RETURN REVIEW REWARD RIBBON ROCKET "
        "SADDLE SAFELY SAFETY SALMON SAMPLE SAVING SCARED SCENE SCHEME SCHOOL SCREEN SCRIPT SEARCH SEASON SECOND SECRET SELDOM SELECT SENIOR SERIES SETTLE SEVERE SHADOW SHIELD SHOULD SHOWER SIGNAL SILENT SILVER SIMPLE SINGLE SISTER SLIGHT SMOOTH SOCCER SOCKET SOURCE SPEECH SPIRIT SPIDER SPIRAL SPREAD SPRING SQUARE STABLE STREAM STREET STRIKE STRING STRONG STUDIO SUDDEN SUFFER SUMMER SUNSET SUPPLY SURELY SURVEY SWITCH SYMBOL SYSTEM "
        "TABLET TARGET TAUGHT TEMPLE TENNIS THANKS THEORY THIRTY THOUGH THREAD THREAT THROAT THROWN TICKET TISSUE TOILET TOMATO TONGUE TOWARD TRAVEL TUNNEL TURTLE TWELVE TWENTY "
        "UNIQUE UNITED UNLESS UNLIKE UPDATE USEFUL "
        "VALLEY VESSEL VICTIM VIOLET VOLUME "
        "WALLET WALNUT WEALTH WEAPON WEEKLY WEIGHT WHISKY WINDOW WINTER WISDOM WIZARD WONDER WOODEN WORKER WORTHY WRITER "
        "YELLOW "
        "ZIPPER",
    ),
    7: _words(
        7,
        "JOURNEY RAINBOW THUNDER DIAMOND VILLAGE KINGDOM "
        "MORNING EVENING WEEKEND HOLIDAY PICTURE MESSAGE "
        "MONSTER CAPTAIN LIBRARY THEATER "
        "ABILITY ABSENCE ACADEMY ACCOUNT ACCURATE ACHIEVE ACQUIRE ADDRESS ADVANCE ADVICE ADVISED AGAINST AIRLINE AIRPORT ALCOHOL ALREADY AMAZING ANALYST ANCIENT ANOTHER ANXIETY ANXIOUS ANYBODY APPLIED APPROVE ARRANGE ARRIVAL ARTICLE ARTIST ASLEEP ATTEMPT ATTRACT AVERAGE "
        "BALANCE BALLOON BATTERY BECAUSE BEDROOM BELIEVE BELOVED BENEATH BENEFIT BESIDES BETWEEN BICYCLE BIOLOGY BLANKET BLOSSOM BROTHER BROUGHT BUILDER BURNING "
        "CABINET CALCIUM CAPITAL CAPTAIN CAREFUL CARRIED CAUTIOUS CENTURY CERTAIN CHANNEL CHAPTER CHARITY CHICKEN CIRCUIT CITIZEN CLASSIC CLIMATE CLOSELY CLOSET CLOTHES COLLECT COLLEGE COMBINE COMFORT COMMAND COMMENT COMPANY COMPARE COMPETE COMPLEX CONCEPT CONCERN CONCERT CONDUCT CONFIRM CONNECT CONSIST CONTACT CONTAIN CONTENT CONTEST CONTEXT CONTROL CONVERT COOKING CORRECT COTTAGE COUNCIL COUNTRY COURAGE CREATED CRYSTAL CULTURE CURRENT "
        "DANCING DEALING DECIDED DECLARE DEFAULT DEFENCE DEFENSE DELIGHT DELIVER DENSITY DESERVE DESPITE DESTROY DEVELOP DEVOTED DIAMOND DIGITAL DISCUSS DISEASE DISPLAY DISTANT DIVERSE DIVORCE DRAWING DRIVING DROPPED DYNAMIC "
        "EARLIER EASTERN ECONOMY EDITION EDUCATE ELEMENT EMBRACE EMOTION EMPEROR EVENING EXACTLY EXAMINE EXAMPLE EXCITED EXCLUDE EXECUTE EXISTED EXPENSE EXPLAIN EXPLORE EXPRESS EXTREME "
        "FACTORY FAILURE FANTASY FARTHER FASHION FEATURE FEDERAL FEATHER FEELING FICTION FIFTEEN FINALLY FINANCE FIREFLY FITNESS FOREIGN FOREVER FORMULA FORTUNE FORWARD FREEDOM FURTHER "
        "GALLERY GENERAL GENETIC GENUINE GLASSES GRAMMAR GRAVITY GREATER GREATEST GROCERY "
        "HAPPILY HARVEST HEALTHY HEARING HELPING HERSELF HIGHWAY HIMSELF HISTORY HOLIDAY HONESTY HOWEVER HUNDRED HUSBAND "
        "ILLEGAL IMAGINE IMPROVE INCLUDE INITIAL INJURED INQUIRE INSIGHT INSPIRE INSTANT INSTEAD INTENSE INTERIM INVOLVE ISLANDS "
        "JOURNAL JOURNEY JUSTICE "
        "KITCHEN "
        "LANDING LARGELY LEATHER LIBERAL LIBRARY LICENSE LIMITED LOGICAL LUGGAGE "
        "MACHINE MANAGED MANAGER MARRIED MASSIVE MAXIMUM MEANING MEASURE MEDICAL MEETING MESSAGE MILLION MINERAL MINIMUM MINUTE MISSILE MISSING MISSION MIXTURE MONITOR MORNING MUSICAL MYSTERY "
        "NATURAL NEITHER NETWORK NEUTRAL NOTHING NUCLEAR NURSERY "
        "OBSERVE OBVIOUS OFFICER OLYMPIC OPENING OPERATE OPINION ORGANIC OUTCOME OUTDOOR OUTLINE OUTSIDE OVERALL "
        "PACKAGE PAINFUL PAINTED PAINTING PARENTS PARKING PARTIAL PARTNER PASSAGE PASSING PASSION PATIENT PATTERN PAYMENT PENALTY PERFECT PERFORM PERHAPS PICKING PLASTIC POPULAR PREDICT PREPARE PRESENT PRETEND PREVENT PRIVATE PROBLEM PROCESS PRODUCE PRODUCT PROFESS PROFILE PROGRAM PROJECT PROMISE PROMOTE PROTECT PROVIDE PUBLISH PURPOSE PURSUIT "
        "QUALITY QUARTER "
        "RAINBOW RAPIDLY READING REALITY RECEIPT RECEIVE RECOVER REFLECT REFUGEE REGULAR RELATED RELEASE REMAIN REMOTE REMOVED REPLACE REQUEST REQUIRE RESERVE RESPECT RESPOND RESTORE RETIRED REVENUE REVERSE ROUTINE RUNNING "
        "SAILING SATISFY SCIENCE SECTION SEEKING SELLING SERIOUS SERVANT SERVICE SESSION SETTING SEVERAL SHADOW SHELTER SHORTLY SHOWING SILENCE SINGING SITTING SOCIETY SOLDIER SOMEHOW SOMEONE SPECIAL SQUADRON STATION STORAGE STRANGE STRETCH STUDENT SUBJECT SUCCESS SUGGEST SUMMARY SUPPORT SUPPOSE SUPREME SURGERY SURNAME SURPLUS SURVIVE SUSPECT SWIMMING "
        "TEACHER TELLING TEXTURE THEATER THEATRE THERAPY THEREBY THINKING THOUGHT THROUGH THUNDER TONIGHT TOURISM TOURIST TRAFFIC TRAINED TRAINING TREATED TRIBUNE TROUBLE TYPICAL "
        "UNHAPPY UNICORN UNKNOWN UNUSUAL USUALLY UTILITY "
        "VARIETY VARIOUS VEHICLE VENTURE VERSION VICTORY VILLAGE VINTAGE VIRTUAL VISITOR "
        "WAITING WALKING WANTING WARNING WEARING WEATHER WEEKEND WELCOME WESTERN WHEREAS WHETHER WHISPER WILLING WINNING WITHOUT WORKING WORRIED WRITING WRITTEN "
        "YOUNGER",
    ),
    8: _words(
        8,
        "MOUNTAIN ELEPHANT COMPUTER BASEBALL FOOTBALL SANDWICH "
        "SUNSHINE MOONLIGHT TREASURE ADVENTURE BIRTHDAY FESTIVAL "
        "UMBRELLA BACKPACK NOTEBOOK KEYBOARD "
        "ABSOLUTE ACADEMIC ACCIDENT ACCURACY ACTIVITY ACTUALLY ADDITION ADEQUATE ADJACENT ADJUSTED ADMIRING ADMITTED ADVANCED ADVISORY AIRPLANE ALLIANCE ALTHOUGH ANALYSIS ANNOUNCE ANNUALLY ANYTHING ANYWHERE APPARENT APPROACH APPROVAL ARGUMENT ARTISTIC ASSEMBLY ATHLETIC ATTITUDE AUDIENCE "
        "BACKYARD BACTERIAL BASEMENT BATHROOM BECOMING BEGINNER BEHAVIOR BIRTHDAY BLESSING BOUNDARY BRILLIANT BROCHURE BUILDING BUSINESS "
        "CALENDAR CAMPAIGN CAPACITY CATEGORY CHAMPION CHEMICAL CHILDREN CLASSICS CLASSIFY CLEANING CLEARING CLIMBING CLOTHING COLLISION COLORFUL COMMERCE COMMONLY COMPLAIN COMPLETE COMPUTER CONCLUDE CONCRETE CONFLICT CONGRESS CONSIDER CONSTANT CONSUMER CONTAINS CONTINUE CONTRACT CONTRARY CONTRAST CONVINCE COUNTING COVERAGE CREATIVE CRITICAL CULTURAL CUSTOMER "
        "DARKNESS DATABASE DAUGHTER DECISION DECORATE DECREASE DEDICATE DELICATE DELIVERY DEMOCRAT DESCRIBE DESIGNER DETAILED DETECTOR DIALOGUE DIAMETER DIGITALLY DIRECTOR DISAGREE DISASTER DISCLOSE DISCOUNT DISCOVER DISORDER DISTANCE DISTINCT DISTRICT DIVIDING DOCUMENT DOMESTIC DOMINATE DOWNHILL DOWNLOAD DOWNWARD "
        "ECONOMIC EDUCATED EDUCATOR ELECTION ELECTRIC ELEPHANT ELEVATOR ELIGIBLE EMBASSY EMERGING EMOTIONS EMPHASIS EMPLOYEE EMPLOYER ENORMOUS ENVELOPE EQUALITY ESTIMATE EVERYDAY EVERYONE EVIDENCE EXCHANGE EXCITING EXERCISE EXISTING EXPECTED EXPLICIT EXPLOSION EXTERNAL "
        "FACILITY FAMILIAR FESTIVAL FIGHTING FLEXIBLE FOOTBALL FORECAST FORMERLY FORTUNATE FRANKLIN FREQUENT FRIENDLY FUNCTION "
        "GENERATE GENEROUS GOODNESS GRADIENT GRADUATE GRAPHICS GRATEFUL GUARDIAN "
        "HANDBOOK HEADLINE HERITAGE HIGHLAND HISTORIC HOMELESS HOMEPAGE HOSPITAL HUMANITY "
        "ICEBERG IDENTIFY IDENTITY INCIDENT INCREASE INDICATE INDUSTRY INNOCENT INSTANCE INTEGRAL INTENDED INTEREST INTERIOR INTERNAL INTERNET INTERVAL INVOLVED ISOLATED "
        "KEYBOARD "
        "LANGUAGE LEARNING LIGHTING LISTENING LITERARY LOCATION "
        "MAGAZINE MAINTAIN MAJORITY MARATHON MARRIAGE MATERIAL MEDIUM MEDICINE MENTALLY MIDNIGHT MILITARY MINISTER MINORITY MOBILITY MODERATE MOONLIGHT MOUNTAIN MOVEMENT MULTIPLE MUSICIAN MYSTERIOUS "
        "NATIONAL NEGATIVE NEIGHBOR NOTEBOOK NUMEROUS "
        "OBSTACLE OCCASION OFFICIAL OPERATOR OPPOSITE OPTIONAL ORDINARY ORGANIC ORIGINAL OUTGOING OUTREACH OVERCOME OVERHEAD OVERLOOK OVERSEAS OVERTIME "
        "PAINTING PARALLEL PARENTAL PARTICLE PASSPORT PASSWORD PATIENCE PEACEFUL PERSONAL PHYSICAL PLANNING PLATFORM PLEASANT POLITICS POPULATE PORTRAIT POSITION POSITIVE POSSIBLE POTENTIAL POWERFUL PRACTICE PRECIOUS PREMIERE PREPARED PRESENCE PRESIDENT PRESSURE PREVIOUS PRINCESS PRIORITY PROBABLY PRODUCER PROGRESS PROHIBIT PROMINENT PROMISED PROPERLY PROPERTY PROPOSAL PROSPECT PROTOCOL PROVIDER PUBLICLY PURCHASE "
        "QUANTITY QUESTION "
        "RAILROAD REACTION RECEIVER RECENTLY RECOVERY REGIONAL REGISTER RELATION RELATIVE RELIABLE RELIGION REMEMBER REPEATED REPORTED RESEARCH RESOURCE RESPONSE RESTRICT REVEALED ROMANTIC "
        "SANDWICH SATURDAY SCHEDULE SEASONAL SECURITY SENTENCE SEPARATE SHIPPING SHOULDER SIDEWALK SLIGHTLY SMOOTHLY SOFTWARE SOLUTION SOMEBODY SOMEWHAT SOUTHERN SPEAKING SPECIFIC STANDARD STANDING STARTING STRANGER STRATEGY STRENGTH STRICTLY STRONGLY STRUGGLE STUDENTS SUDDENLY SUITABLE SUNSHINE SUPERIOR SUPPLIED SURPRISE SURROUND SURVIVAL SWIMMING SYMPATHY SYNDROME "
        "TEACHING TENSION TERRIBLE TERRIFIC TEXTBOOK THEREFORE THOUSAND TOGETHER TOMORROW TOURISTS TRAINING TRANSFER TREASURE TRIANGLE TROPICAL "
        "UMBRELLA UNIVERSE UNLIKELY UPCOMING "
        "VACATION VALUABLE VARIABLE VERTICAL VICTORIA VIOLENCE VISITORS "
        "WEDNESDAY WEEKENDS WHATEVER WILDLIFE WONDERFUL WORKSHOP "
        "YOURSELF",
    ),
}


def pick_secret(length):
    pool = list(WORDS.get(length, ()))
    if not pool:
        raise ValueError(f"No solo words for length {length}")
    return random.choice(pool)
